const letterContainer = document.getElementById("letters");
const optionsContainer = document.getElementById("options");
const userInputSection = document.getElementById("user-input");
const newGameContainer = document.getElementById("new-game");
const newGameButton = document.getElementById("new-game-button");
const canvas = document.getElementById("main-are");
const resultText = document.getElementById("result");

let options = {
    fruits: [
        "Apple",
        "Banana",
        "Orange",
        "Strawberry",
        "Grapes",
        "Watermelon",
        "Mango",
        "Pineapple",
        "Kiwi",
        "Blueberries",
        "Peach",
        "Pear",
        "Cherry",
        "Raspberry",
        "Plum",
        "Lemon",
        "Lime",
        "Avocado",
        "Cantaloupe",
        "Pomegranate",
        "Coconut",
        "Papaya",
        "Cranberry",
        "Blackberry",
        "Apricot",
        "Fig",
        "Date",
        "Guava",
        "Lychee",
        "Tangerine",
    ],
    animals: [
        "Hedgehog",
        "Rhinoceros",
        "Panther",
        "Walrus",
        "Elephant",
        "Giraffe",
        "Horse",
        "Monkey",
        "Gorilla",
        "Penguin",
        "Kangaroo",
        "Dolphin",
        "Panda",
        "Koala",
        "Cheetah",
        "Zebra",
        "Rabbit",
        "Squirrel",
        "Eagle",
        "Butterfly",
        "Turtle",
        "Snake",
        "Crocodile",
        "Giraffe",
        "Hippopotamus",
        "Peacock",
        "Axolotl",
        "Blobfish",
        "Platypus",
        "Sloth",
        "Vampire squid",
        "Sunda colugo",
        "Dugong",
        "Mantis shrimp",
        "Armadillo",
        "Narwhal",
        "Pangolin",
    ],
    unspellable: [
        "Accommodate",
        "Pneumonia",
        "Supercalifragilisticexpialidocious",
        "Indict",
        "Rhythm",
        "Pharaoh",
        "Entrepreneur",
        "Conscientious",
        "Chrysanthemum",
        "Antidisestablishmentarianism",
        "Colonel",
        "Maintenance",
        "Receipt",
        "Exaggerate",
        "Bureaucracy",
        "Miscellaneous",
        "Unparalleled",
        "Synonymous",
        "Manoeuvre",
        "Hierarchy",
        "Broccoli",
        "Onomatopoeia",
        "Diarrhea",
        "Ecclesiastical",
        "Catastrophe",
        "Embarrass",
        "Inoculate",
        "Necessity",
        "Pharaoh",
    ],
};
